### PR TITLE
update surface field to be a string

### PR DESCRIPTION
**Pull request by yetti**
@ninhnguyen @scoen @jrixon 

Updated `surface` field in Banjo SOLR schema instead of changing Banjo as suggested by @ninhnguyen.

### CODE REVIEW

**Comment by terenceingram** [comment]
Do all the records need to be reindexed with this change?

**Comment by ninhnguyen** [comment]
👍

**Comment by yetti** [comment]
@terenceingram yeah, they would need to be reindexed. @scoen said we could do it as an overnight job. Not personally sure how long it takes now to reindex everything.

**Comment by ninhnguyen** [comment]
@terenceingram @scoen @yetti 
Yes. All records will need to be reindexed. And Shaun said that it's OK!
There are records which weren't indexed correctly and to fix them, we'll have to do a full reindex of the corpus.
An example in production is:
Do a search on copies with copy role = 's' and DCM PI is empty returns 665 records.
Add criterion Created By = 'Banjo-System' returns 65 records.
Add criterion Created By != 'Banjo-System' returns 600 records.
The last search is wrong because if I click on one of the results, the Created By is mostly Banjo-System.

**Pull request merged**
