### PR TITLE
maxBoolean increased to 100k

### PR DESCRIPTION
**Pull request by bsingh-nla**
@JonathanShaw , @AaronCMuller , @shuangzhou , @snezanam , @ninhnguyen 
can you please look.

### CODE REVIEW

**Comment by shuangzhou** [comment]
Looks good to me, interesting setting, I'm happy to merge if no one raise objection in the next 2 hours or so.

**Comment by AaronCMuller** [comment]
I really don't feel comfortable making the number of boolean clauses so high.

* Has this been tested that this will be performant and won't knock solr over?
* What happens when there is more than 100,000 items? I can see this happening
* Can the operations that occur on this list actually handle 100,000 items?

**Comment by bsingh-nla** [comment]
- solr on snowy was running for few days with this change and I haven't noticed any performance issue.
- Only "My List" tab in search use this config. We are putting limit on number of items a user can select in banjo. 
- We only got 12000 items in dev, so we can't test if solr can handle 100000 items or not. Solr looks ok on selection of 12000 items.

**Comment by AaronCMuller** [comment]
If we're limited the search to 100,000 then it seems a reasonable limit.

Regarding your first and third point, I don't think performance issues would manifest until we actually try hitting 100,000 items. I understand that we can't currently do this in dev. Is there any guidance from the solr people about this?

I'm also still concerned about being able to do anything with these items.

I'm not going to say that this shouldn't be merged, but I think these issues do need to be considered before this gets to production and I personally don't feel comfortable merging this.

**Comment by bsingh-nla** [comment]
@terenceingram any comments?

**Comment by bsingh-nla** [comment]
Based on the following discussions, I think it is safe to set maxBooleanClauses to 100000.

https://issues.apache.org/jira/browse/SOLR-4586
http://www.gossamer-threads.com/lists/lucene/java-dev/187565

**Comment by JonathanShaw** [comment]
those are interesting reading,  from the look of that first one this problem was quite common previously but they seem to think multi term queries solve it in most cases. are they applicable here?

**Comment by AaronCMuller** [comment]
https://issues.apache.org/jira/browse/SOLR-4586?focusedCommentId=13603799&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13603799

This post is interesting. It states that this should be a non-issue for the query-rewriting stuff now, and even though there can be potentially limit, it will affect perf.

**Comment by bsingh-nla** [comment]
I think multi term queries can't solve our problem. We only got object Id of selected items and we can't use "*" wildcard to search solr - it could return wrong results. For example:
if user have selected 3 items: 123, 124, 125. we can't use query 12* to get these results.

**Comment by AaronCMuller** [comment]
Ah yes, that's unfortunate.

Let's see how we go with the increased limit and go from there. Is everyone happy with that? @terenceingram @bsingh-nla @JonathanShaw

**Comment by JonathanShaw** [comment]
I agree

**Comment by bsingh-nla** [comment]
Me too!

**Pull request merged**
